name: n versioning

on:
  push:
    branches:
      - main

jobs:
  create-version-tag:
    runs-on: ubuntu-latest

    steps:
      # リポジトリをチェックアウト（全ての履歴とタグを取得）
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # libpng15のキャッシュをチェック
      - name: Cache libpng15
        id: cache-libpng15
        uses: actions/cache@v3
        with:
          path: ~/libpng15-install
          key: libpng15-1.5.30-${{ runner.os }}
          restore-keys: |
            libpng15-1.5.30-

      # libpng15をソースからビルド（キャッシュが無い場合のみ）
      - name: Build libpng15 from source
        if: steps.cache-libpng15.outputs.cache-hit != 'true'
        run: |
          # 必要なツールをインストール
          sudo apt update
          sudo apt install -y build-essential zlib1g-dev

          # 作業ディレクトリを作成
          mkdir -p ~/build && cd ~/build

          # libpng 1.5.30をダウンロード
          wget https://download.sourceforge.net/libpng/libpng-1.5.30.tar.gz
          tar -xzf libpng-1.5.30.tar.gz
          cd libpng-1.5.30

          # ホームディレクトリ内のプレフィックスでコンパイル
          ./configure --prefix=$HOME/libpng15-install
          make -j$(nproc)
          make install

      # libpng15をシステムにインストール
      - name: Install libpng15 to system
        run: |
          # キャッシュされたファイルまたは新しくビルドしたファイルをシステムにコピー
          sudo cp -r ~/libpng15-install/lib/* /usr/local/lib/
          sudo cp -r ~/libpng15-install/include/* /usr/local/include/
          
          # システムライブラリパスにシンボリックリンクを作成
          sudo ln -sf /usr/local/lib/libpng15.so.15 /usr/lib/x86_64-linux-gnu/libpng15.so.15
          sudo ln -sf /usr/local/lib/libpng15.so /usr/lib/x86_64-linux-gnu/libpng15.so
          
          # ldcacheを更新
          sudo ldconfig
          
          # インストール確認
          ldconfig -p | grep libpng15

      # 全てのタグを取得（fetch-depth: 0が必要）
      - name: Fetch all tags
        run: git fetch --tags

      # 最新のnで始まるタグを取得(無い場合はn0とする)
      - name: Get latest version tag
        id: get_latest_tag
        run: |
          latest_tag=$(git tag --list 'n*' --sort=-v:refname | head -n 1)
          if [ -z "$latest_tag" ]; then
            echo "latest_tag=n0" >> $GITHUB_ENV
            echo "latest_number=0" >> $GITHUB_ENV
          else
            echo "latest_tag=$latest_tag" >> $GITHUB_ENV
            latest_number=${latest_tag#n}
            echo "latest_number=$latest_number" >> $GITHUB_ENV
          fi

      # 新しいバージョンを計算
      - name: Calculate new version
        id: calculate_version
        run: |
          new_number=$((latest_number + 1))
          echo "new_tag=n$new_number" >> $GITHUB_ENV
        env:
          latest_number: ${{ env.latest_number }}

      # 新しいタグを作成してプッシュ
      - name: Create and push new tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag ${{ env.new_tag }}
          git push origin ${{ env.new_tag }}
